site_name: "CS 61 SI: Spring 2017"
pages:
    - [index.md, "Home"]
    - [dis01_1.md, "Week 1 Dis 2: Binary Integers"]
    - [dis02_1.md, "Week 2 Dis 1: Microprocessors and Floating Point"]
    - [dis02_2.md, "Week 2 Dis 2: Binary and Floating Point"]
    - [dis03_1.md, "Week 3 Dis 1: Boolean algebra"]
    - [dis03_2.md, "Week 3 Dis 2: Boolean algebra"]
    - [dis04_1.md, "Week 4 Dis 1: Combinational Logic Circuits"]
    - [dis04_2.md, "Week 4 Dis 2: Adders, Assembly, Registers, and Memory"]
    - [dis05_1.md, "Week 5 Dis 1: Memory and Finite State Machines"]
    - [dis05_2.md, "Week 5 Dis 2: Midterm Review"]
    - [dis06_1.md, "Week 6 Dis 1: LC3 Datapath"]
theme: readthedocs

