site_name: "CS 61 SI: Spring 2017"
pages:
    - [index.md, "Home"]
    - [dis01_1.md, "Week 1 Dis 2: Binary Integers"]
    - [dis02_1.md, "Week 2 Dis 1: Microprocessors and Floating Point"]
    - [dis02_2.md, "Week 2 Dis 2: Binary and Floating Point"]
    - [dis03_1.md, "Week 3 Dis 1: Boolean algebra"]
theme: readthedocs

